app:
  mem_limit: 300m
  memswap_limit: 1g
  build: .
  ports: 
    - '3333:3333'
  volumes:
    - .:/home/nodejs/app
    - /home/nodejs/node_modules
  #command: /bin/sh -c "while true; do sleep 1000; done"
  command: npm start