app:
  mem_limit: 300m
  memswap_limit: 1g
  build: .
  ports: 
    - '80:3000'
  volumes:
    - .:/home/nodejs/app
    - /home/nodejs/node_modules
  command: /bin/sh -c "while true; do sleep 1000; done"